import Header from "../components/Layout/header";
import Footer from "../components/Layout/footer";
import { Inter_Tight } from 'next/font/google'
import "../globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const interTight = Inter_Tight({
  subsets: ['latin'],
  weight: ['400', '600', '500', '700'],
  style: "normal"
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${interTight.className} antialiased tfc_scroll`} suppressHydrationWarning={true} suppressContentEditableWarning={true}
      >
        <Header />
        <main className="bg-mainBackground">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
